source 'https://rubygems.org'
gem 'aruba'
gem 'amatch'
gem 'gherkin', '>=4.0.0'
# TODO: update to gherkin4 gem 'gherkin_format'
# TODO: update to gherkin4 gem 'gherkin_language'
gem 'rake'
gem 'rubocop'
gem 'term-ansicolor'
gem 'engtagger', '>=0.2.1'
